[package]
name = "parlib"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A barebones parser combinator library, inspired by Haskells parsec"
repository = "https://github.com/angelcerveraroldan/parlib"

[dependencies]
